version: "3.8"
services:
  dron.db:
    image: mysql
    container_name: dron.db
    restart: always
    ports: 
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - "./.docker/mysql/:/var/lib/mysql:rw"