version: "3.8"
services:
  dron.db:
    image: mysql
    container_name: dron.db
    restart: always
    ports: 
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - "./.docker/mysql/:/var/lib/mysql:rw"
  dron_api:
    image: ghcr.io/rtuitlab/cp_hack_dron_api:${TAG?-latest}
    build: "./src"
    container_name: "dron.api"
    environment:
      CP_BACK_DBURI: root:root@tcp(dron.db:3306)/dron_db
    ports:
      - 8081:8081
  proxy:
    image: ghcr.io/rtuitlab/cp_hack_dron_proxy:${TAG?-latest}
    build: .
    ports:
      - 8080:8080