// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0B1t322/CP-Rosseti-Back/ent/module"
	"github.com/0B1t322/CP-Rosseti-Back/ent/moduledependcies"
	"github.com/0B1t322/CP-Rosseti-Back/ent/predicate"
)

// ModuleDependciesQuery is the builder for querying ModuleDependcies entities.
type ModuleDependciesQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ModuleDependcies
	// eager-loading edges.
	withModuleDependcies *ModuleQuery
	withModuleDependOn   *ModuleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModuleDependciesQuery builder.
func (mdq *ModuleDependciesQuery) Where(ps ...predicate.ModuleDependcies) *ModuleDependciesQuery {
	mdq.predicates = append(mdq.predicates, ps...)
	return mdq
}

// Limit adds a limit step to the query.
func (mdq *ModuleDependciesQuery) Limit(limit int) *ModuleDependciesQuery {
	mdq.limit = &limit
	return mdq
}

// Offset adds an offset step to the query.
func (mdq *ModuleDependciesQuery) Offset(offset int) *ModuleDependciesQuery {
	mdq.offset = &offset
	return mdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mdq *ModuleDependciesQuery) Unique(unique bool) *ModuleDependciesQuery {
	mdq.unique = &unique
	return mdq
}

// Order adds an order step to the query.
func (mdq *ModuleDependciesQuery) Order(o ...OrderFunc) *ModuleDependciesQuery {
	mdq.order = append(mdq.order, o...)
	return mdq
}

// QueryModuleDependcies chains the current query on the "ModuleDependcies" edge.
func (mdq *ModuleDependciesQuery) QueryModuleDependcies() *ModuleQuery {
	query := &ModuleQuery{config: mdq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moduledependcies.Table, moduledependcies.FieldID, selector),
			sqlgraph.To(module.Table, module.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, moduledependcies.ModuleDependciesTable, moduledependcies.ModuleDependciesColumn),
		)
		fromU = sqlgraph.SetNeighbors(mdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryModuleDependOn chains the current query on the "ModuleDependOn" edge.
func (mdq *ModuleDependciesQuery) QueryModuleDependOn() *ModuleQuery {
	query := &ModuleQuery{config: mdq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mdq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moduledependcies.Table, moduledependcies.FieldID, selector),
			sqlgraph.To(module.Table, module.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, moduledependcies.ModuleDependOnTable, moduledependcies.ModuleDependOnColumn),
		)
		fromU = sqlgraph.SetNeighbors(mdq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ModuleDependcies entity from the query.
// Returns a *NotFoundError when no ModuleDependcies was found.
func (mdq *ModuleDependciesQuery) First(ctx context.Context) (*ModuleDependcies, error) {
	nodes, err := mdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{moduledependcies.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mdq *ModuleDependciesQuery) FirstX(ctx context.Context) *ModuleDependcies {
	node, err := mdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ModuleDependcies ID from the query.
// Returns a *NotFoundError when no ModuleDependcies ID was found.
func (mdq *ModuleDependciesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{moduledependcies.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mdq *ModuleDependciesQuery) FirstIDX(ctx context.Context) int {
	id, err := mdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ModuleDependcies entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ModuleDependcies entity is not found.
// Returns a *NotFoundError when no ModuleDependcies entities are found.
func (mdq *ModuleDependciesQuery) Only(ctx context.Context) (*ModuleDependcies, error) {
	nodes, err := mdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{moduledependcies.Label}
	default:
		return nil, &NotSingularError{moduledependcies.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mdq *ModuleDependciesQuery) OnlyX(ctx context.Context) *ModuleDependcies {
	node, err := mdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ModuleDependcies ID in the query.
// Returns a *NotSingularError when exactly one ModuleDependcies ID is not found.
// Returns a *NotFoundError when no entities are found.
func (mdq *ModuleDependciesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = &NotSingularError{moduledependcies.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mdq *ModuleDependciesQuery) OnlyIDX(ctx context.Context) int {
	id, err := mdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ModuleDependciesSlice.
func (mdq *ModuleDependciesQuery) All(ctx context.Context) ([]*ModuleDependcies, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mdq *ModuleDependciesQuery) AllX(ctx context.Context) []*ModuleDependcies {
	nodes, err := mdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ModuleDependcies IDs.
func (mdq *ModuleDependciesQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := mdq.Select(moduledependcies.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mdq *ModuleDependciesQuery) IDsX(ctx context.Context) []int {
	ids, err := mdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mdq *ModuleDependciesQuery) Count(ctx context.Context) (int, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mdq *ModuleDependciesQuery) CountX(ctx context.Context) int {
	count, err := mdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mdq *ModuleDependciesQuery) Exist(ctx context.Context) (bool, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mdq *ModuleDependciesQuery) ExistX(ctx context.Context) bool {
	exist, err := mdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModuleDependciesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mdq *ModuleDependciesQuery) Clone() *ModuleDependciesQuery {
	if mdq == nil {
		return nil
	}
	return &ModuleDependciesQuery{
		config:               mdq.config,
		limit:                mdq.limit,
		offset:               mdq.offset,
		order:                append([]OrderFunc{}, mdq.order...),
		predicates:           append([]predicate.ModuleDependcies{}, mdq.predicates...),
		withModuleDependcies: mdq.withModuleDependcies.Clone(),
		withModuleDependOn:   mdq.withModuleDependOn.Clone(),
		// clone intermediate query.
		sql:  mdq.sql.Clone(),
		path: mdq.path,
	}
}

// WithModuleDependcies tells the query-builder to eager-load the nodes that are connected to
// the "ModuleDependcies" edge. The optional arguments are used to configure the query builder of the edge.
func (mdq *ModuleDependciesQuery) WithModuleDependcies(opts ...func(*ModuleQuery)) *ModuleDependciesQuery {
	query := &ModuleQuery{config: mdq.config}
	for _, opt := range opts {
		opt(query)
	}
	mdq.withModuleDependcies = query
	return mdq
}

// WithModuleDependOn tells the query-builder to eager-load the nodes that are connected to
// the "ModuleDependOn" edge. The optional arguments are used to configure the query builder of the edge.
func (mdq *ModuleDependciesQuery) WithModuleDependOn(opts ...func(*ModuleQuery)) *ModuleDependciesQuery {
	query := &ModuleQuery{config: mdq.config}
	for _, opt := range opts {
		opt(query)
	}
	mdq.withModuleDependOn = query
	return mdq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DependentID int `json:"dependent_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ModuleDependcies.Query().
//		GroupBy(moduledependcies.FieldDependentID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mdq *ModuleDependciesQuery) GroupBy(field string, fields ...string) *ModuleDependciesGroupBy {
	group := &ModuleDependciesGroupBy{config: mdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mdq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DependentID int `json:"dependent_id,omitempty"`
//	}
//
//	client.ModuleDependcies.Query().
//		Select(moduledependcies.FieldDependentID).
//		Scan(ctx, &v)
//
func (mdq *ModuleDependciesQuery) Select(fields ...string) *ModuleDependciesSelect {
	mdq.fields = append(mdq.fields, fields...)
	return &ModuleDependciesSelect{ModuleDependciesQuery: mdq}
}

func (mdq *ModuleDependciesQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mdq.fields {
		if !moduledependcies.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mdq.path != nil {
		prev, err := mdq.path(ctx)
		if err != nil {
			return err
		}
		mdq.sql = prev
	}
	return nil
}

func (mdq *ModuleDependciesQuery) sqlAll(ctx context.Context) ([]*ModuleDependcies, error) {
	var (
		nodes       = []*ModuleDependcies{}
		_spec       = mdq.querySpec()
		loadedTypes = [2]bool{
			mdq.withModuleDependcies != nil,
			mdq.withModuleDependOn != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ModuleDependcies{config: mdq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, mdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := mdq.withModuleDependcies; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*ModuleDependcies)
		for i := range nodes {
			fk := nodes[i].DependentID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(module.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "dependent_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.ModuleDependcies = n
			}
		}
	}

	if query := mdq.withModuleDependOn; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*ModuleDependcies)
		for i := range nodes {
			fk := nodes[i].DependentOnID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(module.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "dependent_on_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.ModuleDependOn = n
			}
		}
	}

	return nodes, nil
}

func (mdq *ModuleDependciesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mdq.querySpec()
	return sqlgraph.CountNodes(ctx, mdq.driver, _spec)
}

func (mdq *ModuleDependciesQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mdq *ModuleDependciesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   moduledependcies.Table,
			Columns: moduledependcies.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: moduledependcies.FieldID,
			},
		},
		From:   mdq.sql,
		Unique: true,
	}
	if unique := mdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moduledependcies.FieldID)
		for i := range fields {
			if fields[i] != moduledependcies.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mdq *ModuleDependciesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mdq.driver.Dialect())
	t1 := builder.Table(moduledependcies.Table)
	columns := mdq.fields
	if len(columns) == 0 {
		columns = moduledependcies.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mdq.sql != nil {
		selector = mdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range mdq.predicates {
		p(selector)
	}
	for _, p := range mdq.order {
		p(selector)
	}
	if offset := mdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ModuleDependciesGroupBy is the group-by builder for ModuleDependcies entities.
type ModuleDependciesGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mdgb *ModuleDependciesGroupBy) Aggregate(fns ...AggregateFunc) *ModuleDependciesGroupBy {
	mdgb.fns = append(mdgb.fns, fns...)
	return mdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mdgb *ModuleDependciesGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mdgb.path(ctx)
	if err != nil {
		return err
	}
	mdgb.sql = query
	return mdgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := mdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (mdgb *ModuleDependciesGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(mdgb.fields) > 1 {
		return nil, errors.New("ent: ModuleDependciesGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := mdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) StringsX(ctx context.Context) []string {
	v, err := mdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mdgb *ModuleDependciesGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = fmt.Errorf("ent: ModuleDependciesGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) StringX(ctx context.Context) string {
	v, err := mdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (mdgb *ModuleDependciesGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(mdgb.fields) > 1 {
		return nil, errors.New("ent: ModuleDependciesGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := mdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) IntsX(ctx context.Context) []int {
	v, err := mdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mdgb *ModuleDependciesGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = fmt.Errorf("ent: ModuleDependciesGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) IntX(ctx context.Context) int {
	v, err := mdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (mdgb *ModuleDependciesGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(mdgb.fields) > 1 {
		return nil, errors.New("ent: ModuleDependciesGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := mdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := mdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mdgb *ModuleDependciesGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = fmt.Errorf("ent: ModuleDependciesGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) Float64X(ctx context.Context) float64 {
	v, err := mdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (mdgb *ModuleDependciesGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(mdgb.fields) > 1 {
		return nil, errors.New("ent: ModuleDependciesGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := mdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := mdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mdgb *ModuleDependciesGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = fmt.Errorf("ent: ModuleDependciesGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mdgb *ModuleDependciesGroupBy) BoolX(ctx context.Context) bool {
	v, err := mdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mdgb *ModuleDependciesGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mdgb.fields {
		if !moduledependcies.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mdgb *ModuleDependciesGroupBy) sqlQuery() *sql.Selector {
	selector := mdgb.sql.Select()
	aggregation := make([]string, 0, len(mdgb.fns))
	for _, fn := range mdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mdgb.fields)+len(mdgb.fns))
		for _, f := range mdgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mdgb.fields...)...)
}

// ModuleDependciesSelect is the builder for selecting fields of ModuleDependcies entities.
type ModuleDependciesSelect struct {
	*ModuleDependciesQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mds *ModuleDependciesSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mds.prepareQuery(ctx); err != nil {
		return err
	}
	mds.sql = mds.ModuleDependciesQuery.sqlQuery(ctx)
	return mds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mds *ModuleDependciesSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mds *ModuleDependciesSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mds.fields) > 1 {
		return nil, errors.New("ent: ModuleDependciesSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mds *ModuleDependciesSelect) StringsX(ctx context.Context) []string {
	v, err := mds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mds *ModuleDependciesSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = fmt.Errorf("ent: ModuleDependciesSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mds *ModuleDependciesSelect) StringX(ctx context.Context) string {
	v, err := mds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mds *ModuleDependciesSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mds.fields) > 1 {
		return nil, errors.New("ent: ModuleDependciesSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mds *ModuleDependciesSelect) IntsX(ctx context.Context) []int {
	v, err := mds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mds *ModuleDependciesSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = fmt.Errorf("ent: ModuleDependciesSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mds *ModuleDependciesSelect) IntX(ctx context.Context) int {
	v, err := mds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mds *ModuleDependciesSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mds.fields) > 1 {
		return nil, errors.New("ent: ModuleDependciesSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mds *ModuleDependciesSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mds *ModuleDependciesSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = fmt.Errorf("ent: ModuleDependciesSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mds *ModuleDependciesSelect) Float64X(ctx context.Context) float64 {
	v, err := mds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mds *ModuleDependciesSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mds.fields) > 1 {
		return nil, errors.New("ent: ModuleDependciesSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mds *ModuleDependciesSelect) BoolsX(ctx context.Context) []bool {
	v, err := mds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mds *ModuleDependciesSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{moduledependcies.Label}
	default:
		err = fmt.Errorf("ent: ModuleDependciesSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mds *ModuleDependciesSelect) BoolX(ctx context.Context) bool {
	v, err := mds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mds *ModuleDependciesSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mds.sql.Query()
	if err := mds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
