// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/0B1t322/CP-Rosseti-Back/ent/module"
	"github.com/0B1t322/CP-Rosseti-Back/ent/moduletest"
	"github.com/0B1t322/CP-Rosseti-Back/ent/test"
)

// ModuleTest is the model entity for the ModuleTest schema.
type ModuleTest struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ModuleID holds the value of the "module_id" field.
	ModuleID int `json:"module_id,omitempty"`
	// TestID holds the value of the "test_id" field.
	TestID int `json:"test_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModuleTestQuery when eager-loading is set.
	Edges ModuleTestEdges `json:"edges"`
}

// ModuleTestEdges holds the relations/edges for other nodes in the graph.
type ModuleTestEdges struct {
	// Module holds the value of the Module edge.
	Module *Module `json:"Module,omitempty"`
	// Test holds the value of the Test edge.
	Test *Test `json:"Test,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ModuleOrErr returns the Module value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModuleTestEdges) ModuleOrErr() (*Module, error) {
	if e.loadedTypes[0] {
		if e.Module == nil {
			// The edge Module was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: module.Label}
		}
		return e.Module, nil
	}
	return nil, &NotLoadedError{edge: "Module"}
}

// TestOrErr returns the Test value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModuleTestEdges) TestOrErr() (*Test, error) {
	if e.loadedTypes[1] {
		if e.Test == nil {
			// The edge Test was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: test.Label}
		}
		return e.Test, nil
	}
	return nil, &NotLoadedError{edge: "Test"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModuleTest) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case moduletest.FieldID, moduletest.FieldModuleID, moduletest.FieldTestID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ModuleTest", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModuleTest fields.
func (mt *ModuleTest) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case moduletest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mt.ID = int(value.Int64)
		case moduletest.FieldModuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field module_id", values[i])
			} else if value.Valid {
				mt.ModuleID = int(value.Int64)
			}
		case moduletest.FieldTestID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field test_id", values[i])
			} else if value.Valid {
				mt.TestID = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryModule queries the "Module" edge of the ModuleTest entity.
func (mt *ModuleTest) QueryModule() *ModuleQuery {
	return (&ModuleTestClient{config: mt.config}).QueryModule(mt)
}

// QueryTest queries the "Test" edge of the ModuleTest entity.
func (mt *ModuleTest) QueryTest() *TestQuery {
	return (&ModuleTestClient{config: mt.config}).QueryTest(mt)
}

// Update returns a builder for updating this ModuleTest.
// Note that you need to call ModuleTest.Unwrap() before calling this method if this ModuleTest
// was returned from a transaction, and the transaction was committed or rolled back.
func (mt *ModuleTest) Update() *ModuleTestUpdateOne {
	return (&ModuleTestClient{config: mt.config}).UpdateOne(mt)
}

// Unwrap unwraps the ModuleTest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mt *ModuleTest) Unwrap() *ModuleTest {
	tx, ok := mt.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModuleTest is not a transactional entity")
	}
	mt.config.driver = tx.drv
	return mt
}

// String implements the fmt.Stringer.
func (mt *ModuleTest) String() string {
	var builder strings.Builder
	builder.WriteString("ModuleTest(")
	builder.WriteString(fmt.Sprintf("id=%v", mt.ID))
	builder.WriteString(", module_id=")
	builder.WriteString(fmt.Sprintf("%v", mt.ModuleID))
	builder.WriteString(", test_id=")
	builder.WriteString(fmt.Sprintf("%v", mt.TestID))
	builder.WriteByte(')')
	return builder.String()
}

// ModuleTests is a parsable slice of ModuleTest.
type ModuleTests []*ModuleTest

func (mt ModuleTests) config(cfg config) {
	for _i := range mt {
		mt[_i].config = cfg
	}
}
