// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0B1t322/CP-Rosseti-Back/ent/predicate"
	"github.com/0B1t322/CP-Rosseti-Back/ent/question"
	"github.com/0B1t322/CP-Rosseti-Back/ent/test"
	"github.com/0B1t322/CP-Rosseti-Back/ent/theoreticaltest"
	"github.com/0B1t322/CP-Rosseti-Back/ent/theoreticaltry"
)

// TheoreticalTestUpdate is the builder for updating TheoreticalTest entities.
type TheoreticalTestUpdate struct {
	config
	hooks    []Hook
	mutation *TheoreticalTestMutation
}

// Where appends a list predicates to the TheoreticalTestUpdate builder.
func (ttu *TheoreticalTestUpdate) Where(ps ...predicate.TheoreticalTest) *TheoreticalTestUpdate {
	ttu.mutation.Where(ps...)
	return ttu
}

// SetTestID sets the "test_id" field.
func (ttu *TheoreticalTestUpdate) SetTestID(i int) *TheoreticalTestUpdate {
	ttu.mutation.SetTestID(i)
	return ttu
}

// SetDuration sets the "duration" field.
func (ttu *TheoreticalTestUpdate) SetDuration(i int) *TheoreticalTestUpdate {
	ttu.mutation.ResetDuration()
	ttu.mutation.SetDuration(i)
	return ttu
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (ttu *TheoreticalTestUpdate) SetNillableDuration(i *int) *TheoreticalTestUpdate {
	if i != nil {
		ttu.SetDuration(*i)
	}
	return ttu
}

// AddDuration adds i to the "duration" field.
func (ttu *TheoreticalTestUpdate) AddDuration(i int) *TheoreticalTestUpdate {
	ttu.mutation.AddDuration(i)
	return ttu
}

// ClearDuration clears the value of the "duration" field.
func (ttu *TheoreticalTestUpdate) ClearDuration() *TheoreticalTestUpdate {
	ttu.mutation.ClearDuration()
	return ttu
}

// SetTest sets the "Test" edge to the Test entity.
func (ttu *TheoreticalTestUpdate) SetTest(t *Test) *TheoreticalTestUpdate {
	return ttu.SetTestID(t.ID)
}

// AddQuestionIDs adds the "Question" edge to the Question entity by IDs.
func (ttu *TheoreticalTestUpdate) AddQuestionIDs(ids ...int) *TheoreticalTestUpdate {
	ttu.mutation.AddQuestionIDs(ids...)
	return ttu
}

// AddQuestion adds the "Question" edges to the Question entity.
func (ttu *TheoreticalTestUpdate) AddQuestion(q ...*Question) *TheoreticalTestUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return ttu.AddQuestionIDs(ids...)
}

// AddTheoTryIDs adds the "TheoTry" edge to the TheoreticalTry entity by IDs.
func (ttu *TheoreticalTestUpdate) AddTheoTryIDs(ids ...int) *TheoreticalTestUpdate {
	ttu.mutation.AddTheoTryIDs(ids...)
	return ttu
}

// AddTheoTry adds the "TheoTry" edges to the TheoreticalTry entity.
func (ttu *TheoreticalTestUpdate) AddTheoTry(t ...*TheoreticalTry) *TheoreticalTestUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ttu.AddTheoTryIDs(ids...)
}

// Mutation returns the TheoreticalTestMutation object of the builder.
func (ttu *TheoreticalTestUpdate) Mutation() *TheoreticalTestMutation {
	return ttu.mutation
}

// ClearTest clears the "Test" edge to the Test entity.
func (ttu *TheoreticalTestUpdate) ClearTest() *TheoreticalTestUpdate {
	ttu.mutation.ClearTest()
	return ttu
}

// ClearQuestion clears all "Question" edges to the Question entity.
func (ttu *TheoreticalTestUpdate) ClearQuestion() *TheoreticalTestUpdate {
	ttu.mutation.ClearQuestion()
	return ttu
}

// RemoveQuestionIDs removes the "Question" edge to Question entities by IDs.
func (ttu *TheoreticalTestUpdate) RemoveQuestionIDs(ids ...int) *TheoreticalTestUpdate {
	ttu.mutation.RemoveQuestionIDs(ids...)
	return ttu
}

// RemoveQuestion removes "Question" edges to Question entities.
func (ttu *TheoreticalTestUpdate) RemoveQuestion(q ...*Question) *TheoreticalTestUpdate {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return ttu.RemoveQuestionIDs(ids...)
}

// ClearTheoTry clears all "TheoTry" edges to the TheoreticalTry entity.
func (ttu *TheoreticalTestUpdate) ClearTheoTry() *TheoreticalTestUpdate {
	ttu.mutation.ClearTheoTry()
	return ttu
}

// RemoveTheoTryIDs removes the "TheoTry" edge to TheoreticalTry entities by IDs.
func (ttu *TheoreticalTestUpdate) RemoveTheoTryIDs(ids ...int) *TheoreticalTestUpdate {
	ttu.mutation.RemoveTheoTryIDs(ids...)
	return ttu
}

// RemoveTheoTry removes "TheoTry" edges to TheoreticalTry entities.
func (ttu *TheoreticalTestUpdate) RemoveTheoTry(t ...*TheoreticalTry) *TheoreticalTestUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ttu.RemoveTheoTryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ttu *TheoreticalTestUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ttu.hooks) == 0 {
		if err = ttu.check(); err != nil {
			return 0, err
		}
		affected, err = ttu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TheoreticalTestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ttu.check(); err != nil {
				return 0, err
			}
			ttu.mutation = mutation
			affected, err = ttu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ttu.hooks) - 1; i >= 0; i-- {
			if ttu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ttu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ttu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ttu *TheoreticalTestUpdate) SaveX(ctx context.Context) int {
	affected, err := ttu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ttu *TheoreticalTestUpdate) Exec(ctx context.Context) error {
	_, err := ttu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttu *TheoreticalTestUpdate) ExecX(ctx context.Context) {
	if err := ttu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ttu *TheoreticalTestUpdate) check() error {
	if _, ok := ttu.mutation.TestID(); ttu.mutation.TestCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"Test\"")
	}
	return nil
}

func (ttu *TheoreticalTestUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   theoreticaltest.Table,
			Columns: theoreticaltest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: theoreticaltest.FieldID,
			},
		},
	}
	if ps := ttu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ttu.mutation.Duration(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: theoreticaltest.FieldDuration,
		})
	}
	if value, ok := ttu.mutation.AddedDuration(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: theoreticaltest.FieldDuration,
		})
	}
	if ttu.mutation.DurationCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: theoreticaltest.FieldDuration,
		})
	}
	if ttu.mutation.TestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   theoreticaltest.TestTable,
			Columns: []string{theoreticaltest.TestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: test.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttu.mutation.TestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   theoreticaltest.TestTable,
			Columns: []string{theoreticaltest.TestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: test.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ttu.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.QuestionTable,
			Columns: []string{theoreticaltest.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: question.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttu.mutation.RemovedQuestionIDs(); len(nodes) > 0 && !ttu.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.QuestionTable,
			Columns: []string{theoreticaltest.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: question.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttu.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.QuestionTable,
			Columns: []string{theoreticaltest.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: question.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ttu.mutation.TheoTryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.TheoTryTable,
			Columns: []string{theoreticaltest.TheoTryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: theoreticaltry.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttu.mutation.RemovedTheoTryIDs(); len(nodes) > 0 && !ttu.mutation.TheoTryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.TheoTryTable,
			Columns: []string{theoreticaltest.TheoTryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: theoreticaltry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttu.mutation.TheoTryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.TheoTryTable,
			Columns: []string{theoreticaltest.TheoTryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: theoreticaltry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ttu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theoreticaltest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// TheoreticalTestUpdateOne is the builder for updating a single TheoreticalTest entity.
type TheoreticalTestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TheoreticalTestMutation
}

// SetTestID sets the "test_id" field.
func (ttuo *TheoreticalTestUpdateOne) SetTestID(i int) *TheoreticalTestUpdateOne {
	ttuo.mutation.SetTestID(i)
	return ttuo
}

// SetDuration sets the "duration" field.
func (ttuo *TheoreticalTestUpdateOne) SetDuration(i int) *TheoreticalTestUpdateOne {
	ttuo.mutation.ResetDuration()
	ttuo.mutation.SetDuration(i)
	return ttuo
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (ttuo *TheoreticalTestUpdateOne) SetNillableDuration(i *int) *TheoreticalTestUpdateOne {
	if i != nil {
		ttuo.SetDuration(*i)
	}
	return ttuo
}

// AddDuration adds i to the "duration" field.
func (ttuo *TheoreticalTestUpdateOne) AddDuration(i int) *TheoreticalTestUpdateOne {
	ttuo.mutation.AddDuration(i)
	return ttuo
}

// ClearDuration clears the value of the "duration" field.
func (ttuo *TheoreticalTestUpdateOne) ClearDuration() *TheoreticalTestUpdateOne {
	ttuo.mutation.ClearDuration()
	return ttuo
}

// SetTest sets the "Test" edge to the Test entity.
func (ttuo *TheoreticalTestUpdateOne) SetTest(t *Test) *TheoreticalTestUpdateOne {
	return ttuo.SetTestID(t.ID)
}

// AddQuestionIDs adds the "Question" edge to the Question entity by IDs.
func (ttuo *TheoreticalTestUpdateOne) AddQuestionIDs(ids ...int) *TheoreticalTestUpdateOne {
	ttuo.mutation.AddQuestionIDs(ids...)
	return ttuo
}

// AddQuestion adds the "Question" edges to the Question entity.
func (ttuo *TheoreticalTestUpdateOne) AddQuestion(q ...*Question) *TheoreticalTestUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return ttuo.AddQuestionIDs(ids...)
}

// AddTheoTryIDs adds the "TheoTry" edge to the TheoreticalTry entity by IDs.
func (ttuo *TheoreticalTestUpdateOne) AddTheoTryIDs(ids ...int) *TheoreticalTestUpdateOne {
	ttuo.mutation.AddTheoTryIDs(ids...)
	return ttuo
}

// AddTheoTry adds the "TheoTry" edges to the TheoreticalTry entity.
func (ttuo *TheoreticalTestUpdateOne) AddTheoTry(t ...*TheoreticalTry) *TheoreticalTestUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ttuo.AddTheoTryIDs(ids...)
}

// Mutation returns the TheoreticalTestMutation object of the builder.
func (ttuo *TheoreticalTestUpdateOne) Mutation() *TheoreticalTestMutation {
	return ttuo.mutation
}

// ClearTest clears the "Test" edge to the Test entity.
func (ttuo *TheoreticalTestUpdateOne) ClearTest() *TheoreticalTestUpdateOne {
	ttuo.mutation.ClearTest()
	return ttuo
}

// ClearQuestion clears all "Question" edges to the Question entity.
func (ttuo *TheoreticalTestUpdateOne) ClearQuestion() *TheoreticalTestUpdateOne {
	ttuo.mutation.ClearQuestion()
	return ttuo
}

// RemoveQuestionIDs removes the "Question" edge to Question entities by IDs.
func (ttuo *TheoreticalTestUpdateOne) RemoveQuestionIDs(ids ...int) *TheoreticalTestUpdateOne {
	ttuo.mutation.RemoveQuestionIDs(ids...)
	return ttuo
}

// RemoveQuestion removes "Question" edges to Question entities.
func (ttuo *TheoreticalTestUpdateOne) RemoveQuestion(q ...*Question) *TheoreticalTestUpdateOne {
	ids := make([]int, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return ttuo.RemoveQuestionIDs(ids...)
}

// ClearTheoTry clears all "TheoTry" edges to the TheoreticalTry entity.
func (ttuo *TheoreticalTestUpdateOne) ClearTheoTry() *TheoreticalTestUpdateOne {
	ttuo.mutation.ClearTheoTry()
	return ttuo
}

// RemoveTheoTryIDs removes the "TheoTry" edge to TheoreticalTry entities by IDs.
func (ttuo *TheoreticalTestUpdateOne) RemoveTheoTryIDs(ids ...int) *TheoreticalTestUpdateOne {
	ttuo.mutation.RemoveTheoTryIDs(ids...)
	return ttuo
}

// RemoveTheoTry removes "TheoTry" edges to TheoreticalTry entities.
func (ttuo *TheoreticalTestUpdateOne) RemoveTheoTry(t ...*TheoreticalTry) *TheoreticalTestUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ttuo.RemoveTheoTryIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ttuo *TheoreticalTestUpdateOne) Select(field string, fields ...string) *TheoreticalTestUpdateOne {
	ttuo.fields = append([]string{field}, fields...)
	return ttuo
}

// Save executes the query and returns the updated TheoreticalTest entity.
func (ttuo *TheoreticalTestUpdateOne) Save(ctx context.Context) (*TheoreticalTest, error) {
	var (
		err  error
		node *TheoreticalTest
	)
	if len(ttuo.hooks) == 0 {
		if err = ttuo.check(); err != nil {
			return nil, err
		}
		node, err = ttuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TheoreticalTestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ttuo.check(); err != nil {
				return nil, err
			}
			ttuo.mutation = mutation
			node, err = ttuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ttuo.hooks) - 1; i >= 0; i-- {
			if ttuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ttuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ttuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ttuo *TheoreticalTestUpdateOne) SaveX(ctx context.Context) *TheoreticalTest {
	node, err := ttuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ttuo *TheoreticalTestUpdateOne) Exec(ctx context.Context) error {
	_, err := ttuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttuo *TheoreticalTestUpdateOne) ExecX(ctx context.Context) {
	if err := ttuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ttuo *TheoreticalTestUpdateOne) check() error {
	if _, ok := ttuo.mutation.TestID(); ttuo.mutation.TestCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"Test\"")
	}
	return nil
}

func (ttuo *TheoreticalTestUpdateOne) sqlSave(ctx context.Context) (_node *TheoreticalTest, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   theoreticaltest.Table,
			Columns: theoreticaltest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: theoreticaltest.FieldID,
			},
		},
	}
	id, ok := ttuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing TheoreticalTest.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := ttuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, theoreticaltest.FieldID)
		for _, f := range fields {
			if !theoreticaltest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != theoreticaltest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ttuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ttuo.mutation.Duration(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: theoreticaltest.FieldDuration,
		})
	}
	if value, ok := ttuo.mutation.AddedDuration(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: theoreticaltest.FieldDuration,
		})
	}
	if ttuo.mutation.DurationCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: theoreticaltest.FieldDuration,
		})
	}
	if ttuo.mutation.TestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   theoreticaltest.TestTable,
			Columns: []string{theoreticaltest.TestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: test.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttuo.mutation.TestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   theoreticaltest.TestTable,
			Columns: []string{theoreticaltest.TestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: test.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ttuo.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.QuestionTable,
			Columns: []string{theoreticaltest.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: question.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttuo.mutation.RemovedQuestionIDs(); len(nodes) > 0 && !ttuo.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.QuestionTable,
			Columns: []string{theoreticaltest.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: question.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttuo.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.QuestionTable,
			Columns: []string{theoreticaltest.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: question.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ttuo.mutation.TheoTryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.TheoTryTable,
			Columns: []string{theoreticaltest.TheoTryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: theoreticaltry.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttuo.mutation.RemovedTheoTryIDs(); len(nodes) > 0 && !ttuo.mutation.TheoTryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.TheoTryTable,
			Columns: []string{theoreticaltest.TheoTryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: theoreticaltry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ttuo.mutation.TheoTryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theoreticaltest.TheoTryTable,
			Columns: []string{theoreticaltest.TheoTryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: theoreticaltry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TheoreticalTest{config: ttuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ttuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theoreticaltest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
