// Code generated by entc, DO NOT EDIT.

package submoduletest

const (
	// Label holds the string label denoting the submoduletest type in the database.
	Label = "sub_module_test"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubmoduleID holds the string denoting the submodule_id field in the database.
	FieldSubmoduleID = "submodule_id"
	// EdgeSubModule holds the string denoting the submodule edge name in mutations.
	EdgeSubModule = "SubModule"
	// EdgeTherTest holds the string denoting the thertest edge name in mutations.
	EdgeTherTest = "TherTest"
	// Table holds the table name of the submoduletest in the database.
	Table = "SubModuleTest"
	// SubModuleTable is the table that holds the SubModule relation/edge.
	SubModuleTable = "SubModuleTest"
	// SubModuleInverseTable is the table name for the SubModule entity.
	// It exists in this package in order to avoid circular dependency with the "submodule" package.
	SubModuleInverseTable = "SubModule"
	// SubModuleColumn is the table column denoting the SubModule relation/edge.
	SubModuleColumn = "submodule_id"
	// TherTestTable is the table that holds the TherTest relation/edge.
	TherTestTable = "TheoreticalTest"
	// TherTestInverseTable is the table name for the TheoreticalTest entity.
	// It exists in this package in order to avoid circular dependency with the "theoreticaltest" package.
	TherTestInverseTable = "TheoreticalTest"
	// TherTestColumn is the table column denoting the TherTest relation/edge.
	TherTestColumn = "submoduletest_id"
)

// Columns holds all SQL columns for submoduletest fields.
var Columns = []string{
	FieldID,
	FieldSubmoduleID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
